[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["companies.js"]

[[redirects]]
  from = "/companies.js"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/auth-data.json"
  to = "/404.html"
  status = 404
